server:
  port: 7004
management:
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

data:
  env: NaN
  user:
    username: NaN
    password: NaN

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8001/eureka/

#其中 management 是关于 actuator 相关的，接下来自动刷新配置的时候需要使用。
#data 部分是当无法读取配置中心的配置时，使用此配置，以免项目无法启动。