spring:
  application:
    name: ADMIN-9001
  security:
    user:
      name: "swc"
      password: "920511"
server:
  port: 9001

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8001/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      startup: ${random.int}    #needed to trigger info and endpoint update after restart
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}
management:
  endpoint:
    web:
      exposure:
        include: "*"
    health:
      show-details: always